language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
before_install: gem install bundler
notifications:
  webhooks:
    - https://hooks.pubu.im/services/ewzgqdblbngwt1m
  recipients:
    - akirapanda@newnil.com